# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e61f3321167aa12822c8b8c7127cb5e8fb06425dafe88e92f64c669d85d42bc76fb9ad5eb5516b8623451309ac9cf7f441dd135302ed0fe6fb41ba22f8d9b7

test:
  secret_key_base: f23ddeb9119b5158e3bb4f82912408e934fe1e2b92572deebc06f5b93e2924461288136c260689bd14d608a3623d0bf23109d9fa7b88242ead93e549eb959d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
